### ISSUE TITLE
Windows capture circle

### ISSUE THREAD

**Issue by pit-bob** [ai-ro-bo/Rox.Control.Camera.Xamarin#19]
Windows capture is a profile circle. This needs to be the standard size of camera frame by default.

**Comment by pit-bob** [comment]
Investigate if all platforms easily support shapes.

**Comment by r-o-d-p** [comment]
The capture circle was appearing after camera frame for cropping purposes, so I disabled cropping with:

`cameraCaptureUI.PhotoSettings.AllowCropping = false;`

I am currently using `CaptureCameraUI` and I would need to change to `MediaCapture` for more control.
