### ISSUE TITLE
Android FileUriExposed Exception

### ISSUE THREAD

**Issue by pit-bob** [ai-ro-bo/Rox.Control.Camera.Xamarin#22]
Android is throwing FileUriExposedException as `file://` is no longer supported.

Custom FileProvider will be required.

https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

https://stackoverflow.com/questions/43175014/possible-to-use-multiple-authorities-with-fileprovider

**Comment by r-o-d-p** [comment]
> Custom FileProvider will be required.

I created RoxControlCamera.RoxControlCameraFileProvider

**Comment by r-o-d-p** [comment]
I chnaged the FileProvider to generic implementation called `Rox.FileProvider`.
